// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2A9oYjV-43_bN_L0pwql5fCXVXkwlXiM',
    appId: '1:684968736764:web:82c7030bb6095af2106479',
    messagingSenderId: '684968736764',
    projectId: 'todosapp-cb644',
    authDomain: 'todosapp-cb644.firebaseapp.com',
    storageBucket: 'todosapp-cb644.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw9fm6s_GAjtJTFulHyPI0zPGVwx6PO1E',
    appId: '1:684968736764:android:bb9b321374430545106479',
    messagingSenderId: '684968736764',
    projectId: 'todosapp-cb644',
    storageBucket: 'todosapp-cb644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdd4TD5NW3KzK3h3QkPKnq1dZQ7AL67jY',
    appId: '1:684968736764:ios:99a0d0541c43a9da106479',
    messagingSenderId: '684968736764',
    projectId: 'todosapp-cb644',
    storageBucket: 'todosapp-cb644.appspot.com',
    iosBundleId: 'com.example.todosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdd4TD5NW3KzK3h3QkPKnq1dZQ7AL67jY',
    appId: '1:684968736764:ios:f9e9bfb613c38efb106479',
    messagingSenderId: '684968736764',
    projectId: 'todosapp-cb644',
    storageBucket: 'todosapp-cb644.appspot.com',
    iosBundleId: 'com.example.todosApp.RunnerTests',
  );
}
